# Generated by Django 4.0.6 on 2022-09-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
