# Generated by Django 4.0.6 on 2022-08-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_remove_phones_memory_phones_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peripherals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('producer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Peripheral',
                'verbose_name_plural': 'Peripherals',
            },
        ),
        migrations.AlterModelOptions(
            name='consoles',
            options={'verbose_name': 'Console', 'verbose_name_plural': 'Consoles'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, upload_to='game_images'),
        ),
    ]
