# Generated by Django 4.0.6 on 2022-09-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_us',
            new_name='Article',
        ),
    ]
